### ISSUE TITLE
Depends problem. Laravel 8

### ISSUE THREAD

**Issue by DiMMK4** [sburina/laravel-whmcs-up#10]
Hello,

Laravel 8 used "guzzlehttp/guzzle": "^7.0.1" i have error "sburina/laravel-whmcs-up[v1.0.12, ..., v1.0.13] require guzzlehttp/guzzle ~6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1)".

**Comment by sburina** [comment]
Hi, @DiMMK4 !

Removed the requirement, I hope it is going to work now.
