### ISSUE TITLE
Undefined index: remember_token

### ISSUE THREAD

**Issue by ghost** [sburina/laravel-whmcs-up#3]
When logging out I am getting the following error:

`Undefined index: remember_token`

I am assuming this is because Laravel is trying to use the default `Auth::logout()` function and the remember_token is not available when logging in via WHMCS.

I have been able to fix it but I don't know if this is the correct or best solution.

In the WhmcsUser.php file I added:
```
public function getRememberToken()
{
    return '';
}
```

**Comment by sburina** [comment]
Hello, @tecreasey and thank you for the report.

Unfortunately, I'm unable to test it myself currently, but I think your solution will work. I will just change an emtry string to null, since that's the default if the token is not present. The new release is on it's way.. :)

**Comment by ghost** [comment]
Brilliant. I have updated my version and the issue is solved. Logging a user out now completes without an issue.
