### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by SubrataM3** [sburina/laravel-whmcs-up#5]
Hi,

is it possible to throw some exception , in the following cases like - 

> Invalid IP 127.0.0.1
> Forbidden IP 127.65.4.46

or maybe put them in the $errors variable ? (I'm not sure if this is possible)
I am using this as auth guard.

**Comment by sburina** [comment]
Hi, @SubrataM3 !

Just to make sure, are we talking about the client IPs that should be banned from accessing the app, or something else? If you need to restrict the access to your web app by IP, you should probably use a separate middleware for that purpose.

**Comment by SubrataM3** [comment]
Hi, 
Nope. let me try to explain.
This library uses WHMCS external API, and you need to allow external server's IP in 

> Setup -> General settings -> Security -> API IP Access Restriction

 before using it, but when this IP Access Restriction is configured improperly, the API will return error like above and this is troublesome when using this on the login page, because any kind of error will show "Login credentials does not match", rather than actual error.

**Comment by sburina** [comment]
Currently, the module should detect the connection exception or any other GuzzleHttp exception, but as far as I can see from the [WHMCS docs](https://developers.whmcs.com/api-reference/validatelogin/), there's nothing to indicate the actual reason for authentication failure. The API call seems to return only `success` or `failure` strings in the `result` variable.

**Comment by SubrataM3** [comment]
> Currently, the module should detect the connection exception or any other GuzzleHttp exception, but as far as I can see from the [WHMCS docs](https://developers.whmcs.com/api-reference/validatelogin/), there's nothing to indicate the actual reason for authentication failure. The API call seems to return only `success` or `failure` strings in the `result` variable.

Hello, 
yes, but the message variable contains the reason of failure.
![image](https://user-images.githubusercontent.com/15718377/69030217-e664dd80-09fc-11ea-86e5-7c31a0cb1759.png)
I am using this as authentication provider and i don't get any kind of exception thrown, when the above kind of error happens.
Maybe you should test the API call after removing your IP from "API IP Access Restriction" within WHMCS.

**Comment by sburina** [comment]
Unfortunately, I don't use WHMCS and there's no dev environment available to me at this time. If you could provide a complete transcript of this API request, I'll see what I can do.

**Comment by SubrataM3** [comment]
> Unfortunately, I don't use WHMCS and there's no dev environment available to me at this time. If you could provide a complete transcript of this API request, I'll see what I can do.

By transcript, do you mean raw HTTP request and response?

**Comment by sburina** [comment]
Yes please! If it's not too much to ask, could you please send me the examples for successful authentication, an unsuccessful one, and for the case when the IP is not allowed in WHMCS?

**Comment by sburina** [comment]
[Solved](https://github.com/sburina/laravel-whmcs-up/pull/7/commits/6f43ce074497d2273d50bf585cab93f0985217eb) by @SubrataM3 :)
